### ISSUE TITLE
"make bench" fails the first time

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#29]
I'm not sure what happened here, but after a `make clean` and a `make index`, I then ran `make bench` and got this:

```
[mike@raptorlake search-benchmark-game]$ make bench
--- Benchmarking ---
======================
BENCHMARKING tantivy-0.19 TOP_10_COUNT
/s0/l/search-benchmark-game/engines/tantivy-0.19
--- Warming up ...
- Warm up Run #1 of 1
Traceback (most recent call last):
  File "/s0/l/search-benchmark-game/src/client.py", line 96, in <module>
    for _ in drive(queries_shuffled, search_client, command):
  File "/s0/l/search-benchmark-game/src/client.py", line 50, in drive
    count = client.query(query.query, command)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/s0/l/search-benchmark-game/src/client.py", line 39, in query
    cnt = int(recv)
          ^^^^^^^^^
ValueError: invalid literal for int() with base 10: b"--- Building tantivy's binary ---"
make: *** [Makefile:58: bench] Error 1
[mike@raptorlake search-benchmark-game]$    Compiling tantivy-bench v0.1.0 (/s0/l/search-benchmark-game/engines/tantivy-0.19)
    Finished release [optimized] target(s) in 13.16s
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1019:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make[1]: *** [Makefile:17: serve] Error 101
```

I think we need to fix `client.py` to be resilient to some errant `make` output building things, the first time?

When I ran `make bench` again, it seems to be succeeding (running now).

**Comment by mikemccand** [comment]
OK I found a solution -- we need to route the `echo` lines to stderr, and separate stderr and stdout when reading from the subprocess in `client.py`.  I'll work out a PR...

**Comment by mikemccand** [comment]
I pushed the above fix.
